### PR TITLE
Update supported Python versions

### PR DESCRIPTION
**Pull request by Dunedan**
This updates the list of supported Python versions from 3.4, 3.5 and 3.6
to just 3.7, as that's the version currently used to run the lobby bots
for 0ad and is the only version of Python the bots are currently
properly tested with. Python 3.4 and 3.5 are also already end-of-life,
while Python 3.6 will reach its end-of-life in six months, so it makes
little sense to continue to support these versions.

While already supporting newer Python options would be nice, that'll
require some significant changes as development for SleekXMPP stopped
more than two years ago. There is a fork named Slixmmp as continuation,
but that fork requires at least Python 3.7. By updating the supported
Python versions, this commit lays the groundwork for replacing SleekXMPP
with Slixmpp and the support for newer Python versions.

### CODE REVIEW

**Comment by StanleySweet** [comment]
What's the version on the current lobby server?

**Comment by Dunedan** [comment]
> What's the version on the current lobby server?

As stated in the PR description: Python 3.7 :wink:

**Comment by Oceandragon** [comment]
I do think it's an improvement but I'm a little curious about the not supporting also the newer versions of python. Does sleekxmpp break with later versions of python?
I also agree that we should plan to move to slixmpp.

**Comment by Dunedan** [comment]
> I do think it's an improvement but I'm a little curious about the not supporting also the newer versions of python. Does sleekxmpp break with later versions of python?

SleekXMPP officially supports up to Python 3.6 (https://github.com/fritzy/SleekXMPP/blob/cc1d470397de768ffcc41d2ed5ac3118d19f09f5/setup.py#L40-L44). While I'm not aware of specific problems with Python versions newer than that, I believe there is little benefit of investing time into trying it out, as Slixmpp is the way to go anyway.

**Review by Oceandragon — CHANGES_REQUESTED** [review]
We should update the readme to indicate the specific python version supported.

**Comment by Dunedan** [comment]
I added a note regarding the supported Python version to the README now.

**Pull request merged**
